language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev" # 3.7 development branch
  - "nightly" # currently points to 3.7-dev
  # PyPy versions
  - "pypy"  # PyPy2 2.5.0
  - "pypy3" # Pypy3 2.4.0

install: "pip install -r requirements.txt"

script: nosetests --with-coverage --cover-erase --cover-package=Memnarch

matrix:
  allow_failures:
  # there seems to be an error with nose and coverage
  - python: "3.2"
  - python: "nightly"
  - python: "pypy"
  - python: "pypy3"

after_sucess:
  - CODECLIMATE_REPO_TOKEN=513c8604938d594f1089353a46f9619a1c1ccf0c199d202511271763c3c68eb4 codeclimate-test-reporter

addons:
    code_climate:
        repo_token: 513c8604938d594f1089353a46f9619a1c1ccf0c199d202511271763c3c68eb4